name: Full VPS Backup & Restore (10-min Interval)

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 335  # 5h30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Restore latest VPS backup
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "🔁 Restoring latest VPS backup..."
          cd $GITHUB_WORKSPACE
          rm -rf vps_restore
          mkdir -p vps_restore
          cd vps_restore
          
          # Clone the backups branch
          git clone --branch vps-backups https://$PAT_TOKEN@github.com/${{ github.repository }} . || echo "⚠️ No backups found — starting fresh."
          
          # Find the latest tar.gz file
          LATEST_TAR=$(ls -1tr *.tar.gz 2>/dev/null | tail -n 1)
          
          if [ -f "$LATEST_TAR" ]; then
              echo "✅ Extracting $LATEST_TAR ..."
              sudo tar -xzf "$LATEST_TAR" -C /
              echo "✅ VPS restored from backup."
          else
              echo "⚠️ No tar backup found. Starting with clean VPS."
          fi

      - name: Start Autosave Every 10 Minutes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "💾 Starting 10-min autosave loop..."
          cd $GITHUB_WORKSPACE
          
          nohup bash -c "while true; do
              TIMESTAMP=\$(date '+%Y%m%d_%H%M%S')
              BACKUP_FILE=\"vps_backup_\$TIMESTAMP.tar.gz\"
              
              echo \"📦 Creating full VPS backup \$BACKUP_FILE ...\"
              sudo tar --exclude=$GITHUB_WORKSPACE --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/tmp -czf \$BACKUP_FILE /
              
              # Save to GitHub
              mkdir -p vps_backups_temp
              mv \$BACKUP_FILE vps_backups_temp/
              cd vps_backups_temp
              
              git init -q
              git config user.email 'actions@github.com'
              git config user.name 'github-actions'
              git add --all
              git commit -m \"💾 Full VPS backup \$TIMESTAMP\" -q || true
              git branch -M vps-backups
              git push -f https://$PAT_TOKEN@github.com/${{ github.repository }} vps-backups >/dev/null 2>&1 || true
              cd ..
              rm -rf vps_backups_temp
              
              echo \"✅ Backup \$BACKUP_FILE pushed.\"
              
              sleep 600  # 10 minutes
          done" &
          echo "✅ Autosave loop running in background."

      - name: Keep VPS alive
        run: |
          echo "⏳ VPS running for 5h30..."
          sleep 19800

      - name: Auto Restart
        if: always()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          WORKFLOW_FILE: main.yml
          RESTART_REF: main
        run: |
          echo "♻️ Triggering automatic restart..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_FILE/dispatches" \
            -d "{\"ref\":\"$RESTART_REF\"}"
          echo "✅ Restart request sent!"
